language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
env:
  matrix:
  - PYMATGEN_VERSION=2019.1.13
  - PYMATGEN_VERSION=2019.7.30
before_install:
  - pip install --upgrade pip coverage codecov
install:
  - pip install .
# command to run tests
script:
  - coverage run --source=./dpdispatcher -m unittest -v && coverage report
after_success:
  - codecov
